// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	Id           uuid.UUID    `json:"Id"`
	Username     string       `json:"Username"`
	PasswordHash string       `json:"PasswordHash"`
	CreatedAt    time.Time    `json:"CreatedAt"`
	UpdatedAt    sql.NullTime `json:"UpdatedAt"`
}

type AccountsRole struct {
	Id        uuid.UUID `json:"Id"`
	AccountId uuid.UUID `json:"AccountId"`
	RoleId    uuid.UUID `json:"RoleId"`
	CreatedAt time.Time `json:"CreatedAt"`
}

type Permission struct {
	Id          uuid.UUID      `json:"Id"`
	Name        string         `json:"Name"`
	Description sql.NullString `json:"Description"`
	CreatedAt   time.Time      `json:"CreatedAt"`
}

type Role struct {
	Id        uuid.UUID `json:"Id"`
	Name      string    `json:"Name"`
	CreatedAt time.Time `json:"CreatedAt"`
}

type RolesPermission struct {
	Id           uuid.UUID `json:"Id"`
	RoleId       uuid.UUID `json:"RoleId"`
	PermissionId uuid.UUID `json:"PermissionId"`
	CreatedAt    time.Time `json:"CreatedAt"`
}
